{
 "title": "UPS Monitoring",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "room",
    "label": "Room",
    "query": {
     "query": "label_values(network_ups_tools_device_info,room)"
    }
   },
   {
    "name": "flags",
    "label": "Flags",
    "query": {
     "query": "label_values(network_ups_tools_ups_status{ups=\"$device\"},flag)"
    }
   },
   {
    "name": "device",
    "label": "Device",
    "query": {
     "query": "label_values(network_ups_tools_device_info,ups)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Manufacturer",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_device_info{room=\"$room\", ups=\"$device\"}",
     "legendFormat": "{{mfr}}"
    }
   ]
  },
  {
   "title": "Model",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_device_info{room=\"$room\", ups=\"$device\"}",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Serial",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_device_info{room=\"$room\", ups=\"$device\"}",
     "legendFormat": "{{serial}}"
    }
   ]
  },
  {
   "title": "Battery Runtime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_battery_runtime{job=\"custom/nut_exporter\",room=\"$room\",ups=\"$device\"}",
     "legendFormat": "Runtime"
    }
   ]
  },
  {
   "title": "Battery Charge",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_battery_charge{job=\"custom/nut_exporter\",room=\"$room\",ups=\"$device\"}",
     "legendFormat": "Charge"
    }
   ]
  },
  {
   "title": "Charge & Load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "network_ups_tools_battery_charge{job=\"custom/nut_exporter\", room=\"$room\", ups=\"$device\"}",
     "legendFormat": "Charge"
    },
    {
     "expr": "network_ups_tools_ups_load{job=\"custom/nut_exporter\", room=\"$room\", ups=\"$device\"}",
     "legendFormat": "Load"
    }
   ]
  },
  {
   "title": "UPS Load",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_ups_load{job=\"custom/nut_exporter\",room=\"$room\",ups=\"$device\"}",
     "legendFormat": "Load"
    }
   ]
  },
  {
   "title": "Input/Output Voltage",
   "type": "timeseries",
   "description": "This shows the voltage coming from the grid compared to the nominal value and the standard +/- 5%",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "network_ups_tools_input_voltage{job=\"custom/nut_exporter\", room=\"$room\", ups=\"$device\"}",
     "legendFormat": "Input"
    },
    {
     "expr": "network_ups_tools_output_voltage{job=\"custom/nut_exporter\",room=\"$room\",ups=\"$device\"}",
     "legendFormat": "Output"
    },
    { "expr": "114", "legendFormat": "Acceptable Minimum" },
    { "expr": "126", "legendFormat": "Acceptable Maximum" },
    {
     "expr": "network_ups_tools_input_voltage_nominal{job=\"custom/nut_exporter\",room=\"$room\", ups=\"$device\"}",
     "legendFormat": "Nominal"
    }
   ]
  },
  {
   "title": "Real Power",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_ups_realpower{job=\"custom/nut_exporter\",room=\"$room\",ups=\"$device\"}",
     "legendFormat": "Watts"
    }
   ]
  },
  {
   "title": "Real Power",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "network_ups_tools_ups_realpower{job=\"custom/nut_exporter\",room=\"$room\",ups=\"$device\"}",
     "legendFormat": "Watts"
    }
   ]
  },
  {
   "title": "Flags",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 22 },
   "repeat": "flags",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_ups_status{job=\"custom/nut_exporter\",room=\"$room\",flag=\"$flags\", ups=\"$device\"}",
     "legendFormat": "{{flag}}"
    }
   ]
  }
 ]
}