[ups_monitors]
picluster-monitor ansible_host=192.168.1.10 ansible_user=pi

[ups_monitors:vars]
nut_ups_name        = eaton
nut_ups_description = "Eaton 5SC 1500 - IT-Closet"
nut_room_label      = IT-Closet
# set nut_password via vault or --extra-vars
