maxretry = 3

# When two UPSes of the same model share a host via USB, use 'serial' to
# tell NUT which is which. Run 'lsusb -v' or 'upsc -L' to find serial numbers.
[eaton-a]
  driver = usbhid-ups
  port   = auto
  serial = P138M45E67
  desc   = "Eaton 5SC 1500 - IT-Closet A"

[eaton-b]
  driver = usbhid-ups
  port   = auto
  serial = P138M45E49
  desc   = "Eaton 5SC 1500 - IT-Closet B"
