# powervalue = number of power supplies this UPS feeds on THIS host.
# Set to 0 for UPSes protecting other equipment on the same NUT server.
MONITOR eaton-a@localhost 1 nutuser CHANGEME primary
MONITOR eaton-b@localhost 0 nutuser CHANGEME primary
MINSUPPLIES 1
SHUTDOWNCMD "/sbin/shutdown -h +0"
POLLFREQ 5
POLLFREQALERT 5
HOSTSYNC 15
DEADTIME 15
POWERDOWNFLAG /etc/killpower
RBWARNTIME 43200
NOCOMMWARNTIME 300
FINALDELAY 5
